# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7f2011b8e2a37479d16eff880fb7913322b8343571d5f058f62475f0191ff39c72112c8a9cd56111533adf462769622d019d9aae904c729a8612a0c59e17e36

test:
  secret_key_base: a7f7dfa439b092f17691d6dec746c0e2b1fc1b9730f5ead51deebf7154b52962c1e6b798a665c9372997ee7b2bda5531478c35a7629792c1f855ccd36eb56783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
